#ifndef AUTOGENERATED_H_ 
#define AUTOGENERATED_H_ 

#include "Always.h"
#include "Eventually.h"
#include "Until.h"
#include "Conjunction.h"
#include "Disjunction.h"
#include "STL.h"
#include "Atom.h"
#include "Model.h"
#include "AbsSyn.h"


class AutoGenerated : public Model { 

 private: 

 public: 
    AutoGenerated(AbsSyn::InputData m);
    ~AutoGenerated();
 }; 
 #endif
